language: haskell
ghc: 7.6.3
notifications:
  email: false
install: 
        
script:
   - cabal install cabal-dev
   - cabal-dev install --ghc-options=-DNO_INTERPRET_QUOTES Nomyx-Language/Nomyx-Language.cabal Nomyx/Nomyx.cabal"
